"""
Ship Doctor - Gemini Analyzer
=============================
Module 7: Medical Document AI Assistant

Uses Google Gemini API for intelligent medical document analysis.

Author: VitalPlunder Team

DISCLAIMER: This tool is for informational purposes only and does NOT
provide medical advice, diagnosis, or treatment recommendations.
Always consult qualified healthcare professionals for medical decisions.
"""

import os
import json

# Optional: Try to import Gemini
try:
    import google.generativeai as genai
    GEMINI_AVAILABLE = True
except ImportError:
    GEMINI_AVAILABLE = False


class GeminiAnalyzer:
    """
    Medical Document Analyzer using Google Gemini API
    
    Provides intelligent summaries and highlights of medical documents.
    """
    
    # Medical disclaimer
    DISCLAIMER = """
    ⚠️ IMPORTANT MEDICAL DISCLAIMER ⚠️
    
    This analysis is generated by AI for INFORMATIONAL PURPOSES ONLY.
    It does NOT constitute medical advice, diagnosis, or treatment.
    
    - Always consult qualified healthcare professionals
    - Do not make medical decisions based on this analysis
    - Seek immediate medical attention for emergencies
    - This tool cannot replace professional medical judgment
    
    The AI may make errors or miss important information.
    Use this as a starting point for discussion with your doctor.
    """
    
    # Analysis prompt template
    ANALYSIS_PROMPT = """
    You are a helpful medical document assistant. Analyze the following medical report text and provide:
    
    1. **Simple Summary**: A brief, easy-to-understand summary of the report (2-3 sentences)
    
    2. **Key Findings**: List the main test results and their values
    
    3. **Highlighted Values**: Identify any values marked as:
       - HIGH or ELEVATED
       - LOW or DECREASED  
       - ABNORMAL or CRITICAL
       
    4. **General Health Guidance**: Provide general, non-medical suggestions like:
       - Lifestyle considerations
       - Questions to ask your doctor
       - Areas that may need follow-up
    
    IMPORTANT: 
    - Do NOT provide medical diagnoses
    - Do NOT recommend specific treatments
    - Always encourage consulting healthcare professionals
    - Keep language simple and accessible
    
    Medical Report Text:
    {document_text}
    
    Provide your analysis in a clear, structured format.
    """
    
    def __init__(self):
        """Initialize Gemini analyzer"""
        self.model = None
        self._initialize_gemini()
    
    def _initialize_gemini(self):
        """Initialize Gemini API if available"""
        if not GEMINI_AVAILABLE:
            print("⚠️ Gemini API not available. Install google-generativeai.")
            return
        
        api_key = os.getenv('GEMINI_API_KEY')
        if not api_key:
            print("⚠️ GEMINI_API_KEY not set in environment variables.")
            return
        
        try:
            genai.configure(api_key=api_key)
            self.model = genai.GenerativeModel('gemini-pro')
            print("✅ Gemini API initialized successfully")
        except Exception as e:
            print(f"⚠️ Failed to initialize Gemini: {e}")
    
    def analyze_document(self, document_text):
        """
        Analyze medical document using Gemini API
        
        Args:
            document_text: Extracted text from medical document
            
        Returns:
            Analysis result with summary and highlights
        """
        if not document_text or len(document_text.strip()) < 20:
            return {
                'success': False,
                'error': 'Document text too short for analysis'
            }
        
        # Try Gemini API
        if self.model:
            try:
                result = self._gemini_analysis(document_text)
                result['disclaimer'] = self.DISCLAIMER
                return result
            except Exception as e:
                print(f"Gemini API error: {e}")
        
        # Fall back to rule-based analysis
        result = self._rule_based_analysis(document_text)
        result['disclaimer'] = self.DISCLAIMER
        return result
    
    def _gemini_analysis(self, document_text):
        """Perform analysis using Gemini API"""
        prompt = self.ANALYSIS_PROMPT.format(document_text=document_text[:4000])
        
        response = self.model.generate_content(prompt)
        
        return {
            'success': True,
            'analysis': response.text,
            'method': 'gemini_api',
            'model': 'gemini-pro'
        }
    
    def _rule_based_analysis(self, document_text):
        """
        Rule-based analysis when Gemini is unavailable
        
        Provides basic parsing and highlighting of medical values.
        """
        text_lower = document_text.lower()
        lines = document_text.split('\n')
        
        # Extract findings
        findings = {
            'normal': [],
            'elevated': [],
            'low': [],
            'abnormal': []
        }
        
        for line in lines:
            line_clean = line.strip()
            if not line_clean:
                continue
            
            line_lower = line_clean.lower()
            
            # Categorize findings
            if any(flag in line_lower for flag in ['high', 'elevated', 'above']):
                findings['elevated'].append(line_clean)
            elif any(flag in line_lower for flag in ['low', 'decreased', 'below']):
                findings['low'].append(line_clean)
            elif any(flag in line_lower for flag in ['abnormal', 'critical', 'alert']):
                findings['abnormal'].append(line_clean)
            elif 'normal' in line_lower or re.search(r'\d+.*normal', line_lower):
                findings['normal'].append(line_clean)
        
        # Build analysis
        analysis_parts = []
        
        analysis_parts.append("## Simple Summary")
        analysis_parts.append("This is an automated analysis of your medical document. " +
                             "Please review with your healthcare provider.")
        
        analysis_parts.append("\n## Key Findings")
        
        if findings['elevated']:
            analysis_parts.append("\n### ⚠️ Elevated Values:")
            for item in findings['elevated'][:5]:
                analysis_parts.append(f"- {item}")
        
        if findings['low']:
            analysis_parts.append("\n### ⚠️ Low Values:")
            for item in findings['low'][:5]:
                analysis_parts.append(f"- {item}")
        
        if findings['abnormal']:
            analysis_parts.append("\n### 🚨 Abnormal Values:")
            for item in findings['abnormal'][:5]:
                analysis_parts.append(f"- {item}")
        
        if findings['normal']:
            analysis_parts.append("\n### ✅ Normal Values:")
            for item in findings['normal'][:5]:
                analysis_parts.append(f"- {item}")
        
        analysis_parts.append("\n## General Guidance")
        analysis_parts.append("- Discuss any highlighted values with your doctor")
        analysis_parts.append("- Ask about recommended follow-up tests")
        analysis_parts.append("- Maintain a healthy lifestyle")
        analysis_parts.append("- Keep copies of your medical records")
        
        return {
            'success': True,
            'analysis': '\n'.join(analysis_parts),
            'method': 'rule_based',
            'findings': findings,
            'note': 'Using rule-based analysis. For AI-powered insights, configure Gemini API.'
        }
    
    def get_health_guidance(self, findings):
        """
        Generate general health guidance based on findings
        
        Args:
            findings: Dictionary of categorized findings
            
        Returns:
            List of guidance suggestions
        """
        guidance = [
            {
                'title': 'Consult Your Doctor',
                'description': 'Schedule a follow-up to discuss your results',
                'icon': '👨‍⚕️'
            },
            {
                'title': 'Keep Records',
                'description': 'Maintain copies of all medical documents',
                'icon': '📋'
            },
            {
                'title': 'Track Changes',
                'description': 'Compare with previous results to monitor trends',
                'icon': '📊'
            }
        ]
        
        # Add specific guidance based on findings
        if findings.get('elevated') or findings.get('abnormal'):
            guidance.insert(0, {
                'title': 'Priority Follow-up',
                'description': 'Some values need attention. Contact your healthcare provider.',
                'icon': '⚠️'
            })
        
        return guidance


# Import re for rule-based analysis
import re

# Create singleton instance
gemini_analyzer = GeminiAnalyzer()


def analyze_medical_document(document_text):
    """Convenience function for document analysis"""
    return gemini_analyzer.analyze_document(document_text)


def get_medical_disclaimer():
    """Get the medical disclaimer text"""
    return gemini_analyzer.DISCLAIMER
